### ISSUE TITLE
Conf tests are failing

### ISSUE THREAD

**Issue by ignatenkobrain** [TomasTomecek/pretty-git-prompt#35]
```rust
failures:

---- conf::tests::test_load_default_config stdout ----
	thread 'conf::tests::test_load_default_config' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 6, message: "could not find repository from \'.\'" }', src/libcore/result.rs:906:4

---- conf::tests::test_values_is_present stdout ----
	thread 'conf::tests::test_values_is_present' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 6, message: "could not find repository from \'.\'" }', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- conf::tests::test_lower_version stdout ----
	thread 'conf::tests::test_lower_version' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 6, message: "could not find repository from \'.\'" }', src/libcore/result.rs:906:4
note: Panic did not include expected string 'Config should be using version '1', instead is using '0''
---- conf::tests::test_empty_config stdout ----
	thread 'conf::tests::test_empty_config' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 6, message: "could not find repository from \'.\'" }', src/libcore/result.rs:906:4
note: Panic did not include expected string ''version' is missing in config file.'

failures:
    conf::tests::test_empty_config
    conf::tests::test_load_default_config
    conf::tests::test_lower_version
    conf::tests::test_values_is_present

test result: FAILED. 3 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out
```

@TomasTomecek said that he will fix it!

**Comment by TomasTomecek** [comment]
The issue is that the test suite is meant to be run from this git repo (or basically any git repo). I'll make it work anywhere.

Pity rust doesn't have such an advanced testing framework such as pytest.
